name: Update Zerotier DNS

on:
  repository_dispatch:
    types: zt-dns-update
  push:
    branches:
      - master
  schedule:
    - cron: '*/60 * * * *'

jobs:
  dns:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Zerotier DNS
        env:
          ZEROTIER_AUTH_TOKEN: ${{ secrets.ZEROTIER_AUTH_TOKEN }}
          ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
          CLOUDFLARE_AUTH_TOKEN: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: ./zerotier-cloudflare-dns.sh
